config/routes.rb
Rails.application.routes.draw do
  get 'newsletters/create'
  namespace(:admin){
    resources :assistances
    resources :newsletters 
    resources(:notices){
      resources :notice_images do
        put :sort, on: :collection
        get :unpublished, on: :member 
        get :published, on: :member 
      end
    }
    resources :abouts, :only => [:edit, :update] 
    resources :configurations, :only => [:edit, :update] 
    get 'homes/index'
    resources(:product_labels) do
      collection do
        get :check_images
      end  
    end
    resources(:product_lines ){
      resources :product_categories
      resources(:products){
        resources :product_images do
          put :sort, on: :collection
          get :unpublished, on: :member 
          get :published, on: :member
        end
        collection do
          get :check_images
          get :check_product_download
        end
      } 
    }
    resources :users
    root :to => 'homes#index'
  }

    
  localized do
    
    namespace(:furnitures){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show] 
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
    }
    namespace(:toys){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show]  
      resources(:homes, :only => [:index]){
        
      }   
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
      
    }
    namespace(:domestic_utilities){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show]
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
    }
    resources :newsletters, :only => [:create]
    resources :news, :only => [:index, :show] 
    resources :user_sessions, :only => [:new, :create, :destroy] 
    root :to => 'homes#index'
    get 'homes/load_image'
    match '/login' => 'user_sessions#new', via: :get  
    match '/logout' => 'user_sessions#destroy', via: :get
    match '/about' => 'homes#about', via: :get
    match '/assistance' =>  'homes#assistance', via: :get

  end

end

app/models/notice_image.rb
class NoticeImage < ActiveRecord::Base
  #attr_accessible :title
  
  translates :title, :fallbacks_for_empty_translations => true
  accepts_nested_attributes_for :translations
  globalize_accessors :locales => I18n.available_locales, :attributes => translated_attribute_names    
  
  has_attached_file :image_notice, styles: {thumb: "150x150#", internal: "300x300#", big: "800×800>"},processors: [:thumbnail, :compression]
  validates_attachment_content_type :image_notice, :content_type => /\Aimage\/.*\Z/
  validates_presence_of :image_notice
  
  belongs_to :notice
  
  default_scope { order("priority ASC, id") }
end

app/controllers/admin/notice_images_controller.rb
class Admin::NoticeImagesController < ApplicationController
  layout "admin"
  access_control do
      allow logged_in
  end
  before_filter :load_notice
  def index
    @notice_images = @notice.notice_images.all_active
  end

  def show
    @notice_image = @notice.notice_images.find(params[:id])
  end

  def new
    @notice_image = @notice.notice_images.build
  end

  def create
    if !params[:notice_image][:attachments_array].blank?    
      params[:notice_image][:attachments_array].each do |file|
        
        params.permit!
        image_save = @notice.notice_images.build(:image_notice => file)
        image_save.save
      end
      redirect_to admin_notice_notice_images_path(@notice)
    else
      render :action => 'new'
    end   
    #@notice_image = @notice.notice_images.build(params[:notice_image])
    #if @notice_image.save
    #  redirect_to [:admin, @notice, @notice_image], :notice => "Successfully created notice image."
    #else
    #  render :action => 'new'
    #end
  end

  def edit
    @notice_image = @notice.notice_images.find(params[:id])
  end

  def update
    params.permit!
    @notice_image = @notice.notice_images.find(params[:id])
    if @notice_image.update_attributes(params[:notice_image])
      redirect_to [:admin, @notice, @notice_image], :notice  => "Successfully updated notice image."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @notice_image = @notice.notice_images.find(params[:id])
    @notice_image.newdestroy
    redirect_to admin_notice_notice_images_path(@notice), :notice => "Successfully destroyed notice image."
  end
  
  
  def sort
    params[:order].each do |key,value|
      @notice.notice_images.find(value[:id]).update_attribute(:priority,value[:position])
    end
    render :nothing => true
  end
  
  
  def unpublished
   @notice_image = @notice.notice_images.find(params[:id])
   if !@notice_image.blank?
     @notice_image.published = false
     @notice_image.save
   end
  end
  
  def published
   @notice_image = @notice.notice_images.find(params[:id])
   if !@notice_image.blank?
     @notice_image.published = true
     @notice_image.save
   end
  end
  
  
  def load_notice
    @notice = Notice.find(params[:notice_id])
  end
end

app/helpers/admin/notice_images_helper.rb
module Admin::NoticeImagesHelper
end

app/views/admin/notice_images/_form.html.haml
= form_for [:admin, @notice, @notice_image], :html => { :multipart => true } do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      = f.error_messages

  .box-body 
    -if @notice_image.id.blank?
      .form-group
        %label Imagens
        %input{:multiple => "multiple", :name => "notice_image[attachments_array][]", :type => "file"}/    
    -else
      #tabs.nav-tabs-custom
        %ul.nav.nav-tabs
          - NoticeImage.globalize_locales.sort!{|x,y| y <=> x }.each do |show|
            - if NoticeImage.globalize_locales.first == show
              - class_locales = "active "
            - else
              - class_locales = ""
            %li{class: class_locales}
              =link_to(translate_option(show), "##{show}", "data-toggle": "tab")
        .tab-content
          - NoticeImage.globalize_locales.sort!{|x,y| y <=> x }.each do |show|
            - if NoticeImage.globalize_locales.first == show
              - class_locales = "active "
            - else
              - class_locales = ""
            - class_locales = "#{class_locales}tab-pane"
            %div{id: show, class: class_locales}
              - NoticeImage.globalize_attribute_names.each do |lang|       
                - if lang[-2, 2] == "#{show[-2,2].downcase}"
                  -if !(lang[0, 4] == "slug")
                    .form-group
                      = f.label lang
                      -if lang[0, 4] == "desc"
                        = f.text_area lang, rows: "3", :class => "form-control tinymce"
                      -else
                        = f.text_field lang, :class => "form-control"
      .form-group
        = f.label :image_notice
        = f.file_field :image_notice, :class => "form-control"
      - if @notice_image.image_notice.file?
        .form-group
          =image_tag(@notice_image.image_notice.url("internal"))
      .form-group 
        = f.label :published
        = f.check_box :published
  .box-footer
    =f.submit nil, class: "btn btn-primary"

app/views/admin/notice_images/_notice_image.haml
-if notice_image.published
  -show_class = ""
-else
  -show_class = "line_unpublished"
%tr{:class => "table-line #{show_class}",:"data-id" => "#{notice_image.id}"}
  %td
    -if notice_image.image_notice.file?
      = image_tag(notice_image.image_notice.url("thumb"))
  %td= notice_image.title
  %td.class_published= show_boolean(notice_image.published)
  %td  
    = link_to t("show"), [:admin, @notice, notice_image], class: "btn btn-default"
    = link_to t("edit"), edit_admin_notice_notice_image_path(@notice, notice_image), class: "btn btn-default"
    = link_to t("destroy"),[:admin, @notice, notice_image],  method: :delete , data:{confirm: t("msg_delete")}, class: "btn btn-danger"
    %span.btn-change-published
      -if notice_image.published
        = link_to t("unpublished"), unpublished_admin_notice_notice_image_path(@notice, notice_image), class: "btn btn-warning", remote: true
      -else
        = link_to t("published"), published_admin_notice_notice_image_path(@notice, notice_image), class: "btn btn-success", remote: true

app/views/admin/notice_images/edit.html.haml
%section.content-header
  %h1
    =NoticeImage.model_name.human() 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=NoticeImage.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title
            =NoticeImage.model_name.human() 
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_notice_notice_images_path(@notice), class:"btn btn-default"

app/views/admin/notice_images/index.html.haml
-content_for :globalvar do
  %script
    var url_put= "#{sort_admin_notice_notice_images_path(@notice)}";
%section.content-header
  %h1
    =NoticeImage.model_name.human()
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=NoticeImage.model_name.human()  
/ Main content
%section.content
  .row
    .col-xs-12
      %p= link_to "Nova #{NoticeImage.model_name.human()} ", new_admin_notice_notice_image_path(@notice), class: "btn btn-primary"
      .box
        .box-header
          %h3.box-title="#{NoticeImage.model_name.human(count: 2)}  - #{@notice.title}"
        .box-body.table-responsive.no-padding
          %table.table.table-hover
            %thead
              %tr
                %th=t("activerecord.attributes.notice_image.notice_images")
                %th=t("activerecord.attributes.notice_image.title")
                %th=t("activerecord.attributes.notice_image.published")
                %th=t("actions")
            %tbody.sortable
              - for notice_image in @notice_images
                =render notice_image
      %p= link_to "Nova #{NoticeImage.model_name.human()} ", new_admin_notice_notice_image_path(@notice), class: "btn btn-primary"

app/views/admin/notice_images/new.html.haml
%section.content-header
  %h1
    =NoticeImage.model_name.human() 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=NoticeImage.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title 
            =NoticeImage.model_name.human() 
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_notice_notice_images_path(@notice), class: "btn btn-default"

app/views/admin/notice_images/published.js.haml
$("tr[data-id='#{@notice_image.id}']").removeClass('line_unpublished');
$("tr[data-id='#{@notice_image.id}'] td.class_published").html("#{show_boolean(@notice_image.published)}");
$("tr[data-id='#{@notice_image.id}'] .btn-change-published").html('#{link_to t("unpublished"), unpublished_admin_notice_notice_image_path(@notice, @notice_image), class: "btn btn-warning", remote: true}');

app/views/admin/notice_images/show.html.haml
%section.content-header
  %h1
    =NoticeImage.model_name.human()   
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=NoticeImage.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title=NoticeImage.model_name.human() 
        .box-body  
          %p
            %b="#{t("activerecord.attributes.notice_image.title")}:"
            %br
            = @notice_image.title
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.notice_image.published")}:"
            %br
            = show_boolean(@notice_image.published)
        - if @notice_image.image_notice.file?
          .box-body  
            %p
              %b="#{t("activerecord.attributes.notice_image.image_notice")}:"
              %br
              =image_tag(@notice_image.image_notice.url("big"))
        
  = link_to t("back_list"), admin_notice_notice_images_path(@notice), :class => "btn btn-default"
  = link_to t("edit"), edit_admin_notice_notice_image_path(@notice,@notice_image), class: "btn btn-default"
  = link_to "Novo #{NoticeImage.model_name.human()} ", new_admin_notice_notice_image_path(@notice), class: "btn btn-primary"

app/views/admin/notice_images/unpublished.js.haml
$("tr[data-id='#{@notice_image.id}']").addClass('line_unpublished');
$("tr[data-id='#{@notice_image.id}'] td.class_published").html("#{show_boolean(@notice_image.published)}");
$("tr[data-id='#{@notice_image.id}'] .btn-change-published").html('#{link_to t("published"), published_admin_notice_notice_image_path(@notice, @notice_image), class: "btn btn-success btn-change-published", remote: true}');