config/routes.rb
Rails.application.routes.draw do
  get 'newsletters/create'
  namespace(:admin){
    resources :assistances
    resources :newsletters 
    resources(:notices){
      resources :notice_images do
        put :sort, on: :collection
        get :unpublished, on: :member 
        get :published, on: :member 
      end
    }
    resources :abouts, :only => [:edit, :update] 
    resources :configurations, :only => [:edit, :update] 
    get 'homes/index'
    resources(:product_labels) do
      collection do
        get :check_images
      end  
    end
    resources(:product_lines ){
      resources :product_categories
      resources(:products){
        resources :product_images do
          put :sort, on: :collection
          get :unpublished, on: :member 
          get :published, on: :member
        end
        collection do
          get :check_images
          get :check_product_download
        end
      } 
    }
    resources :users
    root :to => 'homes#index'
  }

    
  localized do
    
    namespace(:furnitures){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show] 
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
    }
    namespace(:toys){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show]  
      resources(:homes, :only => [:index]){
        
      }   
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
      
    }
    namespace(:domestic_utilities){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show]
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
    }
    resources :newsletters, :only => [:create]
    resources :news, :only => [:index, :show] 
    resources :user_sessions, :only => [:new, :create, :destroy] 
    root :to => 'homes#index'
    get 'homes/load_image'
    match '/login' => 'user_sessions#new', via: :get  
    match '/logout' => 'user_sessions#destroy', via: :get
    match '/about' => 'homes#about', via: :get
    match '/assistance' =>  'homes#assistance', via: :get

  end

end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
  #attr_accessible :title_telesales, :title_contact, :title_institutional, :title_virtual_catalog, :title_download_virtual_catalog, :text_download_virtual_catalog, :title_download, :title_search, :title_more, :title_product_data, :title_length, :title_width, :title_height, :title_weight, :title_colors, :title_description, :title_product_specifications, :title_quantity, :title_colors, :title_see_the_product, :title_production_xplast, :title_contact_us
  
  translates :title_telesales, :title_contact, :title_institutional, :title_virtual_catalog, :title_download_virtual_catalog, :text_download_virtual_catalog, :title_download, :title_enter, :title_search, :title_more, :title_product_data, :title_length, :title_width, :title_height, :title_weight, :title_colors, :title_description, :title_product_specifications, :title_quantity, :title_see_the_product, :title_production_xplast, :title_contact_us, :phone_number, :sac_number, :description_about, :description_distributed, :title_assistance, :title_packed_product_specifications_pack, :title_parts, :title_nothing_found, :title_phone, :title_address, :title_neighborhood, :title_city, :title_email, :title_site, :title_service_text, :title_currency_exchange, :title_know_more, :title_news, :title_events,:title_download_images, :title_source_news, :title_send_button, :title_share, :newsletter_success,  :newsletter_error, :fallbacks_for_empty_translations => true
  accepts_nested_attributes_for :translations
  globalize_accessors :locales => I18n.available_locales, :attributes => translated_attribute_names
  
  
  has_attached_file :catalog_furniture
  do_not_validate_attachment_file_type :catalog_furniture
  
  has_attached_file :catalog_toys
  do_not_validate_attachment_file_type :catalog_toys
  
  has_attached_file :catalog_domestic_utility
  do_not_validate_attachment_file_type :catalog_domestic_utility
  
end

app/controllers/admin/configurations_controller.rb
class Admin::ConfigurationsController < ApplicationController
  layout "admin"
  access_control do
      allow logged_in
  end
  def index
    @configurations = ::Configuration.all_active
  end

  def show
    @configuration = ::Configuration.find(params[:id])
  end

  def new
    @configuration = ::Configuration.new
  end

  def create
    params.permit!
    @configuration = ::Configuration.new(params[:configuration])
    if @configuration.save
      redirect_to [:admin, @configuration], :notice => "Successfully created configuration."
    else
      render :action => 'new'
    end
  end

  def edit
    @configuration = ::Configuration.find(1)
  end

  def update
    params.permit!
    @configuration = ::Configuration.find(1)
    if @configuration.update_attributes(params[:configuration])
      redirect_to edit_admin_configuration_path("xplast"), :notice  => "Successfully updated configuration."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @configuration = ::Configuration.find(params[:id])
    @configuration.newdestroy
    redirect_to admin_configurations_url, :notice => "Successfully destroyed configuration."
  end
end

app/helpers/admin/configurations_helper.rb
module Admin::ConfigurationsHelper
end

app/views/admin/configurations/_form.html.haml
= form_for [:admin, @configuration] do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      = f.error_messages
  .box-body 
    #tabs.nav-tabs-custom
      %ul.nav.nav-tabs
        - ::Configuration.globalize_locales.sort!{|x,y| y <=> x }.each do |show|
          - if ::Configuration.globalize_locales.first == show
            - class_locales = "active "
          - else
            - class_locales = ""
          %li{class: class_locales}
            =link_to(translate_option(show), "##{show}", "data-toggle": "tab")
      .tab-content
        - ::Configuration.globalize_locales.sort!{|x,y| y <=> x }.each do |show|
          - if ::Configuration.globalize_locales.first == show
            - class_locales = "active "
          - else
            - class_locales = ""
          - class_locales = "#{class_locales}tab-pane"
          %div{id: show, class: class_locales}
            - ::Configuration.globalize_attribute_names.each do |lang|       
              - if lang[-2, 2] == "#{show[-2,2].downcase}"
                .form-group 
                  = f.label lang
                  -if lang[0, 4] == "desc"
                    = f.text_area lang, rows: "3", :class => "form-control tinymce"
                  -else
                    = f.text_field lang, :class => "form-control"      
    .form-group 
      = f.label :sac_mail
      = f.text_field :sac_mail, class: "form-control"
    .form-group 
      = f.label :link_facebook
      = f.text_field :link_facebook, class: "form-control"
    .form-group 
      = f.label :link_instagram
      = f.text_field :link_instagram, class: "form-control"
    .form-group 
      = f.label :link_linkedin
      = f.text_field :link_linkedin, class: "form-control"
    .form-group
      = f.label :catalog_furniture
      = f.file_field :catalog_furniture, :class => "form-control"
    - if @configuration.catalog_furniture.file?
      .form-group
        =link_to("Catalogo Atual de Moveis", @configuration.catalog_furniture.url, :target => "_blank")
    .form-group
      = f.label :catalog_toys
      = f.file_field :catalog_toys, :class => "form-control"
    - if @configuration.catalog_toys.file?
      .form-group
        =link_to("Catalogo Atual de Brinquedos", @configuration.catalog_toys.url, :target => "_blank")            
    .form-group
      = f.label :catalog_domestic_utility
      = f.file_field :catalog_domestic_utility, :class => "form-control"
    - if @configuration.catalog_domestic_utility.file?
      .form-group
        =link_to("Catalogo Atual de Utilidade Domestica", @configuration.catalog_domestic_utility.url, :target => "_blank")
  .box-footer
    =f.submit nil, class: "btn btn-primary"

app/views/admin/configurations/edit.html.haml
%section.content-header
  %h1
    =Configuration.model_name.human() 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Configuration.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title
            =Configuration.model_name.human() 
        / /.box-header
        / form start
        = render 'form'
      
        %p

app/views/admin/configurations/index.html.haml
%section.content-header
  %h1
    =Configuration.model_name.human()   
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Configuration.model_name.human()  
/ Main content
%section.content
  .col-xs-12
    %p= link_to "Novo #{Configuration.model_name.human()} ", new_admin_configuration_path, class: "btn btn-primary"
    .box
      .box-header
        %h3.box-title="#{Configuration.model_name.human(count: 2)} Cadastrados"
      .box-body.table-responsive.no-padding
        %table.table.table-hover
          %tr
            %th=t("activerecord.attributes.configuration.title_telesales")
            %th=t("activerecord.attributes.configuration.title_contact")
            %th=t("activerecord.attributes.configuration.title_institutional")
            %th=t("activerecord.attributes.configuration.title_virtual_catalog")
            %th=t("activerecord.attributes.configuration.title_download_virtual_catalog")
            %th=t("activerecord.attributes.configuration.text_download_virtual_catalog")
            %th=t("activerecord.attributes.configuration.title_download")
            %th=t("activerecord.attributes.configuration.title_search")
            %th=t("activerecord.attributes.configuration.title_more")
            %th=t("activerecord.attributes.configuration.title_product_data")
            %th=t("activerecord.attributes.configuration.title_length")
            %th=t("activerecord.attributes.configuration.title_width")
            %th=t("activerecord.attributes.configuration.title_height")
            %th=t("activerecord.attributes.configuration.title_weight")
            %th=t("activerecord.attributes.configuration.title_colors")
            %th=t("activerecord.attributes.configuration.title_description")
            %th=t("activerecord.attributes.configuration.title_product_specifications")
            %th=t("activerecord.attributes.configuration.title_quantity")
            %th=t("activerecord.attributes.configuration.title_colors")
            %th=t("activerecord.attributes.configuration.title_see_the_product")
            %th=t("activerecord.attributes.configuration.title_production_xplast")
            %th=t("activerecord.attributes.configuration.title_contact_us")
            %th=t("activerecord.attributes.configuration.published")
            %th=t("actions")
          - for configuration in @configurations
            %tr
              %td= configuration.title_telesales
              %td= configuration.title_contact
              %td= configuration.title_institutional
              %td= configuration.title_virtual_catalog
              %td= configuration.title_download_virtual_catalog
              %td= configuration.text_download_virtual_catalog
              %td= configuration.title_download
              %td= configuration.title_search
              %td= configuration.title_more
              %td= configuration.title_product_data
              %td= configuration.title_length
              %td= configuration.title_width
              %td= configuration.title_height
              %td= configuration.title_weight
              %td= configuration.title_colors
              %td= configuration.title_description
              %td= configuration.title_product_specifications
              %td= configuration.title_quantity
              %td= configuration.title_colors
              %td= configuration.title_see_the_product
              %td= configuration.title_production_xplast
              %td= configuration.title_contact_us
              %td= show_boolean(configuration.published)
              %td  
                = link_to t("show"), [:admin, configuration], class: "btn btn-default"
                = link_to t("edit"), edit_admin_configuration_path(configuration), class: "btn btn-default"
                = link_to t("destroy"),[:admin, configuration],  method: :delete , data:{confirm: t("msg_delete")}, class: "btn btn-default"
    %p= link_to "Novo #{Configuration.model_name.human()} ", new_admin_configuration_path, class: "btn btn-primary"

app/views/admin/configurations/new.html.haml
%section.content-header
  %h1
    =Configuration.model_name.human() 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Configuration.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title 
            =Configuration.model_name.human() 
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_configurations_path, class: "btn btn-default"

app/views/admin/configurations/show.html.haml
%section.content-header
  %h1
    =Configuration.model_name.human()   
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Configuration.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title=Configuration.model_name.human() 
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_telesales")}:"
            %br
            = @configuration.title_telesales
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_contact")}:"
            %br
            = @configuration.title_contact
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_institutional")}:"
            %br
            = @configuration.title_institutional
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_virtual_catalog")}:"
            %br
            = @configuration.title_virtual_catalog
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_download_virtual_catalog")}:"
            %br
            = @configuration.title_download_virtual_catalog
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.text_download_virtual_catalog")}:"
            %br
            = @configuration.text_download_virtual_catalog
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_download")}:"
            %br
            = @configuration.title_download
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_search")}:"
            %br
            = @configuration.title_search
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_more")}:"
            %br
            = @configuration.title_more
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_product_data")}:"
            %br
            = @configuration.title_product_data
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_length")}:"
            %br
            = @configuration.title_length
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_width")}:"
            %br
            = @configuration.title_width
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_height")}:"
            %br
            = @configuration.title_height
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_weight")}:"
            %br
            = @configuration.title_weight
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_colors")}:"
            %br
            = @configuration.title_colors
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_description")}:"
            %br
            = @configuration.title_description
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_product_specifications")}:"
            %br
            = @configuration.title_product_specifications
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_quantity")}:"
            %br
            = @configuration.title_quantity
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_colors")}:"
            %br
            = @configuration.title_colors
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_see_the_product")}:"
            %br
            = @configuration.title_see_the_product
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_production_xplast")}:"
            %br
            = @configuration.title_production_xplast
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.title_contact_us")}:"
            %br
            = @configuration.title_contact_us
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.configuration.published")}:"
            %br
            = show_boolean(@configuration.published)
        
  = link_to t("back_list"), admin_configurations_path, :class => "btn btn-default"
  = link_to t("edit"), edit_admin_configuration_path(@configuration), class: "btn btn-default"
  = link_to "Novo #{Configuration.model_name.human()} ", new_admin_configuration_path, class: "btn btn-primary"