config/routes.rb
Rails.application.routes.draw do
  get 'newsletters/create'
  namespace(:admin){
    resources :assistances
    resources :newsletters 
    resources(:notices){
      resources :notice_images do
        put :sort, on: :collection
        get :unpublished, on: :member 
        get :published, on: :member 
      end
    }
    resources :abouts, :only => [:edit, :update] 
    resources :configurations, :only => [:edit, :update] 
    get 'homes/index'
    resources(:product_labels) do
      collection do
        get :check_images
      end  
    end
    resources(:product_lines ){
      resources :product_categories
      resources(:products){
        resources :product_images do
          put :sort, on: :collection
          get :unpublished, on: :member 
          get :published, on: :member
        end
        collection do
          get :check_images
          get :check_product_download
        end
      } 
    }
    resources :users
    root :to => 'homes#index'
  }

    
  localized do
    
    namespace(:furnitures){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show] 
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
    }
    namespace(:toys){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show]  
      resources(:homes, :only => [:index]){
        
      }   
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
      
    }
    namespace(:domestic_utilities){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show]
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
    }
    resources :newsletters, :only => [:create]
    resources :news, :only => [:index, :show] 
    resources :user_sessions, :only => [:new, :create, :destroy] 
    root :to => 'homes#index'
    get 'homes/load_image'
    match '/login' => 'user_sessions#new', via: :get  
    match '/logout' => 'user_sessions#destroy', via: :get
    match '/about' => 'homes#about', via: :get
    match '/assistance' =>  'homes#assistance', via: :get

  end

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  #attr_accessible :title, :email
  validates :title, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/controllers/admin/newsletters_controller.rb
class Admin::NewslettersController < ApplicationController
  layout "admin"
  access_control do
      allow logged_in
  end
  def index
    @newsletters = Newsletter.all_active('created_at desc')
  end

  def show
    redirect_to admin_newsletters_url
    #@newsletter = Newsletter.find(params[:id])
  end

  def new
    @newsletter = Newsletter.new
  end

  def create
    params.permit!
    @newsletter = Newsletter.new(params[:newsletter])
    if @newsletter.save
      redirect_to admin_newsletters_url, :notice => "Successfully created newsletter."
    else
      render :action => 'new'
    end
  end

  def edit
    @newsletter = Newsletter.find(params[:id])
  end

  def update
    params.permit!
    @newsletter = Newsletter.find(params[:id])
    if @newsletter.update_attributes(params[:newsletter])
      redirect_to admin_newsletters_url, :notice  => "Successfully updated newsletter."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.newdestroy
    redirect_to admin_newsletters_url, :notice => "Successfully destroyed newsletter."
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_filter :load_configurations  
  def create
    params.permit!
    @newsletter = Newsletter.new(params[:newsletter])
    if @newsletter.save
      @erro = false
    else
      @erro = true
    end
  end
  
end

app/helpers/admin/newsletters_helper.rb
module Admin::NewslettersHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/admin/newsletters/_form.html.haml
= form_for [:admin, @newsletter] do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      = f.error_messages

  .box-body        
    .form-group 
      = f.label :title
      = f.text_field :title, class: "form-control"
    .form-group 
      = f.label :email
      = f.text_field :email, class: "form-control"
  .box-footer
    =f.submit nil, class: "btn btn-primary"

app/views/admin/newsletters/edit.html.haml
%section.content-header
  %h1
    =Newsletter.model_name.human() 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Newsletter.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title
            =Newsletter.model_name.human() 
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_newsletters_path, class:"btn btn-default"

app/views/admin/newsletters/index.html.haml
%section.content-header
  %h1
    =Newsletter.model_name.human()   
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Newsletter.model_name.human()  
/ Main content
%section.content
  .row
    .col-xs-12
      %p= link_to "Nova #{Newsletter.model_name.human()} ", new_admin_newsletter_path, class: "btn btn-primary"
      .box
        .box-header
          %h3.box-title="#{Newsletter.model_name.human(count: 2)} Cadastrados"
        .box-body.table-responsive.no-padding
          %table.table.table-hover
            %tr
              %th=t("activerecord.attributes.newsletter.title")
              %th=t("activerecord.attributes.newsletter.email")
              %th=t("activerecord.attributes.newsletter.created_at")
              %th=t("actions")
            - for newsletter in @newsletters
              %tr
                %td= newsletter.title
                %td= newsletter.email
                %td= l(newsletter.created_at, :format => :long)
                %td  
                  = link_to t("edit"), edit_admin_newsletter_path(newsletter), class: "btn btn-default"
                  = link_to t("destroy"),[:admin, newsletter],  method: :delete , data:{confirm: t("msg_delete")}, class: "btn btn-danger"
      %p= link_to "Nova #{Newsletter.model_name.human()} ", new_admin_newsletter_path, class: "btn btn-primary"

app/views/admin/newsletters/new.html.haml
%section.content-header
  %h1
    =Newsletter.model_name.human() 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Newsletter.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title 
            =Newsletter.model_name.human() 
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_newsletters_path, class: "btn btn-default"

app/views/admin/newsletters/show.html.haml
%section.content-header
  %h1
    =Newsletter.model_name.human()   
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Newsletter.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title=Newsletter.model_name.human() 
        .box-body  
          %p
            %b="#{t("activerecord.attributes.newsletter.title")}:"
            %br
            = @newsletter.title
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.newsletter.email")}:"
            %br
            = @newsletter.email
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.newsletter.published")}:"
            %br
            = show_boolean(@newsletter.published)
        
  = link_to t("back_list"), admin_newsletters_path, :class => "btn btn-default"
  = link_to t("edit"), edit_admin_newsletter_path(@newsletter), class: "btn btn-default"
  = link_to "Novo #{Newsletter.model_name.human()} ", new_admin_newsletter_path, class: "btn btn-primary"