config/routes.rb
Rails.application.routes.draw do
  get 'newsletters/create'
  namespace(:admin){
    resources :assistances
    resources :newsletters 
    resources(:notices){
      resources :notice_images do
        put :sort, on: :collection
        get :unpublished, on: :member 
        get :published, on: :member 
      end
    }
    resources :abouts, :only => [:edit, :update] 
    resources :configurations, :only => [:edit, :update] 
    get 'homes/index'
    resources(:product_labels) do
      collection do
        get :check_images
      end  
    end
    resources(:product_lines ){
      resources :product_categories
      resources(:products){
        resources :product_images do
          put :sort, on: :collection
          get :unpublished, on: :member 
          get :published, on: :member
        end
        collection do
          get :check_images
          get :check_product_download
        end
      } 
    }
    resources :users
    root :to => 'homes#index'
  }

    
  localized do
    
    namespace(:furnitures){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show] 
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
    }
    namespace(:toys){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show]  
      resources(:homes, :only => [:index]){
        
      }   
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
      
    }
    namespace(:domestic_utilities){
      resources :categories, :only => [:show] 
      resources :products, :only => [:show]
      root :to => 'homes#index'
      match '/search' => 'homes#search', via: :get
    }
    resources :newsletters, :only => [:create]
    resources :news, :only => [:index, :show] 
    resources :user_sessions, :only => [:new, :create, :destroy] 
    root :to => 'homes#index'
    get 'homes/load_image'
    match '/login' => 'user_sessions#new', via: :get  
    match '/logout' => 'user_sessions#destroy', via: :get
    match '/about' => 'homes#about', via: :get
    match '/assistance' =>  'homes#assistance', via: :get

  end

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  #attr_accessible :title, :description, :title_source
  
  translates :title, :description, :fallbacks_for_empty_translations => true
  accepts_nested_attributes_for :translations
  globalize_accessors :locales => I18n.available_locales, :attributes => translated_attribute_names
  
  has_attached_file :notice_image, styles: { internal: "300x300>", thumb: "50x50>", home: "555x226>"},processors: [:thumbnail, :compression]
  validates_attachment_content_type :notice_image, :content_type => /\Aimage\/.*\Z/
  
  
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  
  has_many :notice_images
  
  # Metodo para listar todos publicados
  def self.all_published(ordernar ='', limit = '')
    order_show = 'id'
    if !ordernar.blank? 
      order_show = ordernar
    end
    if !limit.blank?    
      where(active: true, published: true).order(order_show).limit(limit)
    else
      where(active: true, published: true).order(order_show)
    end
  end
  
  def self.all_events_published(ordernar ='', limit = '')
    order_show = 'id'
    if !ordernar.blank? 
      order_show = ordernar
    end
    if !limit.blank?    
      where("`notices`.`active` = 1 AND `notices`.`published` = 1 AND `notices`.`its_an_event` = 1 AND `notices`.`stop_event` >= '#{Date.today}'").order(order_show).limit(limit)
    else
      where("`notices`.`active` = 1 AND `notices`.`published` = 1 AND `notices`.`its_an_event` = 1 AND `notices`.`stop_event` >= '#{Date.today}'").order(order_show)
    end
  end
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < ApplicationController
  layout "admin"
  access_control do
      allow logged_in
  end
  def index
    @notices = Notice.all_active
  end

  def show
    @notice = Notice.find(params[:id])
  end

  def new
    @notice = Notice.new
  end

  def create
    params.permit!
    @notice = Notice.new(params[:notice])
    if @notice.save
      redirect_to [:admin, @notice], :notice => "Successfully created notice."
    else
      render :action => 'new'
    end
  end

  def edit
    @notice = Notice.find(params[:id])
  end

  def update
    params.permit!
    @notice = Notice.find(params[:id])
    if @notice.update_attributes(params[:notice])
      redirect_to [:admin, @notice], :notice  => "Successfully updated notice."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @notice = Notice.find(params[:id])
    @notice.newdestroy
    redirect_to admin_notices_url, :notice => "Successfully destroyed notice."
  end
end

app/helpers/admin/notices_helper.rb
module Admin::NoticesHelper
end

app/views/admin/notices/_form.html.haml
=content_for :footer do
  = tinymce_assets
  = tinymce
  
= form_for [:admin, @notice] do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      = f.error_messages

  .box-body        
    #tabs.nav-tabs-custom
      %ul.nav.nav-tabs
        - Notice.globalize_locales.sort!{|x,y| y <=> x }.each do |show|
          - if Notice.globalize_locales.first == show
            - class_locales = "active "
          - else
            - class_locales = ""
          %li{class: class_locales}
            =link_to(translate_option(show), "##{show}", "data-toggle": "tab")
      .tab-content
        - Notice.globalize_locales.sort!{|x,y| y <=> x }.each do |show|
          - if Notice.globalize_locales.first == show
            - class_locales = "active "
          - else
            - class_locales = ""
          - class_locales = "#{class_locales}tab-pane"
          %div{id: show, class: class_locales}
            - Notice.globalize_attribute_names.each do |lang|       
              - if lang[-2, 2] == "#{show[-2,2].downcase}"
                -if !(lang[0, 4] == "slug")
                  .form-group
                    = f.label lang
                    -if lang[0, 4] == "desc"
                      = f.text_area lang, rows: "3", :class => "form-control tinymce"
                    -else
                      = f.text_field lang, :class => "form-control"
    .form-group 
      = f.label :title_source
      = f.text_field :title_source, class: "form-control"      
    .form-group 
      = f.label :link_source
      = f.text_field :link_source, class: "form-control"
    .form-group
      = f.label :notice_image
      = f.file_field :notice_image, :class => "form-control"
    - if @notice.notice_image.file?
      .form-group
        =image_tag(@notice.notice_image.url)  
    .form-group 
      = f.label :its_an_event
      = f.check_box :its_an_event
    .form-group 
      = f.label :start_event
      = f.date_select :start_event
    .form-group 
      = f.label :stop_event
      = f.date_select :stop_event
    .form-group 
      = f.label :published
      = f.check_box :published
  .box-footer
    =f.submit nil, class: "btn btn-primary"

app/views/admin/notices/edit.html.haml
%section.content-header
  %h1
    =Notice.model_name.human() 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Notice.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title
            =Notice.model_name.human() 
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_notices_path, class:"btn btn-default"

app/views/admin/notices/index.html.haml
%section.content-header
  %h1
    =Notice.model_name.human()   
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Notice.model_name.human()  
/ Main content
%section.content
  .row
    .col-xs-12
      %p= link_to "Nova #{Notice.model_name.human()} ", new_admin_notice_path, class: "btn btn-primary"
      .box
        .box-header
          %h3.box-title="#{Notice.model_name.human(count: 2)} Cadastrados"
        .box-body.table-responsive.no-padding
          %table.table.table-hover
            %tr
              %th=t("activerecord.attributes.notice.notice_image")
              %th=t("activerecord.attributes.notice.title")
              %th=t("activerecord.attributes.notice.published")
              %th=t("actions")
            - for notice in @notices
              %tr
                %td
                  -if notice.notice_image.file?
                    =image_tag(notice.notice_image.url("thumb"))
                %td= notice.title
                %td= show_boolean(notice.published)
                %td  
                  = link_to t("show"), [:admin, notice], class: "btn btn-default"
                  = link_to t("edit"), edit_admin_notice_path(notice), class: "btn btn-default"
                  = link_to t("destroy"),[:admin, notice],  method: :delete , data:{confirm: t("msg_delete")}, class: "btn btn-default"
                  = link_to NoticeImage.model_name.human(count: 2), admin_notice_notice_images_path(notice), class: "btn btn-success"
      %p= link_to "Nova #{Notice.model_name.human()} ", new_admin_notice_path, class: "btn btn-primary"

app/views/admin/notices/new.html.haml
%section.content-header
  %h1
    =Notice.model_name.human() 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Notice.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title 
            =Notice.model_name.human() 
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_notices_path, class: "btn btn-default"

app/views/admin/notices/show.html.haml
%section.content-header
  %h1
    =Notice.model_name.human()   
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Notice.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title=Notice.model_name.human() 
        .box-body  
          %p
            %b="#{t("activerecord.attributes.notice.title")}:"
            %br
            = @notice.title
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.notice.description")}:"
            %br
            = raw(@notice.description)
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.notice.title_source")}:"
            %br
            = @notice.title_source
        - if @notice.notice_image.file?
          .box-body  
            %p
              %b="#{t("activerecord.attributes.notice.notice_image")}:"
              %br
              =image_tag(@notice.notice_image.url)  
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.notice.published")}:"
            %br
            = show_boolean(@notice.published)
        
  = link_to t("back_list"), admin_notices_path, :class => "btn btn-default"
  = link_to t("edit"), edit_admin_notice_path(@notice), class: "btn btn-default"
  = link_to "Novo #{Notice.model_name.human()} ", new_admin_notice_path, class: "btn btn-primary"